import { Company } from "./types";

export const companies: Company [] = [
	{
	  id: 1,
	  name: "Tech Innovators",
	  description: "A leading software company specializing in AI solutions.",
	  price: 500000,
	  industry: "Technology",
	  image: "/images/company1.jpg",
	  seller: "John Doe",
	},
	{
	  id: 2,
	  name: "Green Energy Solutions",
	  description: "Renewable energy startup focusing on solar and wind power.",
	  price: 750000,
	  industry: "Energy",
	  image: "/images/company2.jpg",
	  seller: "Alice Smith",
	},
	{
	  id: 3,
	  name: "NextGen Robotics",
	  description: "A robotics company developing AI-driven automation.",
	  price: 1200000,
	  industry: "Technology",
	  image: "/images/company3.jpg",
	  seller: "Michael Johnson",
	},
	{
	  id: 4,
	  name: "EcoFresh Organics",
	  description: "Organic food production company committed to sustainability.",
	  price: 300000,
	  industry: "Food & Agriculture",
	  image: "/images/company4.jpg",
	  seller: "Sarah Wilson",
	},
	{
	  id: 5,
	  name: "AutoDrive Systems",
	  description: "Self-driving car technology company.",
	  price: 2000000,
	  industry: "Automotive",
	  image: "/images/company5.jpg",
	  seller: "David Brown",
	},
	{
	  id: 6,
	  name: "FinTech Innovators",
	  description: "A digital banking and finance solutions provider.",
	  price: 900000,
	  industry: "Finance",
	  image: "/images/company6.jpg",
	  seller: "Emma Davis",
	},
	{
	  id: 7,
	  name: "HealthFirst Medical",
	  description: "Medical tech startup offering AI-powered diagnostics.",
	  price: 1100000,
	  industry: "Healthcare",
	  image: "/images/company7.jpg",
	  seller: "James White",
	},
	{
	  id: 8,
	  name: "Fashion Forward",
	  description: "Sustainable clothing brand with a global presence.",
	  price: 250000,
	  industry: "Fashion",
	  image: "/images/company8.jpg",
	  seller: "Olivia Martin",
	},
	{
	  id: 9,
	  name: "EdTech Pioneers",
	  description: "Online education platform for tech skills and courses.",
	  price: 650000,
	  industry: "Education",
	  image: "/images/company9.jpg",
	  seller: "William Lee",
	},
	{
	  id: 10,
	  name: "SpaceXplorers",
	  description: "Aerospace startup working on space tourism projects.",
	  price: 5000000,
	  industry: "Aerospace",
	  image: "/images/company10.jpg",
	  seller: "Sophia Anderson",
	},
  ];
  